### ISSUE TITLE
latest version not passing yarn:nsp

### ISSUE THREAD

**Issue by eamagdalena** [hmcts/nodejs-logging#19]
The latest version is not passing the yarn:nsp task, so applications that require it cannot be built on jenkins:

│ Regular Expression Denial of Service                                                                                                          
│ Name          │ debug                                                                                                                                         │
│ CVSS          │ 3.7 (Low)                                                                                                                                     │
│ Installed     │ 2.2.0                                                                                                                                         │
│ Vulnerable    │ <= 2.6.8 || >= 3.0.0 <= 3.0.1                                                                                                                 │
│ Patched       │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                                                                                                  │
│ Path          │ fees-register-admin-web@1.0.0 > @hmcts/nodejs-logging@1.4.2 > log4js@2.3.12 > mailgun-js@0.7.15 > debug@2.2.0                                 │
│ More Info     │ https://nodesecurity.io/advisories/534

**Comment by timja-kainos** [comment]
@eamagdalena I think its an upstream problem, if you could either try fixing it in log4js or at least report an issue there if you find it is there fault?
